In [1]:
import numpy as np
arr = [10,20,30,40,50]
arr

[10, 20, 30, 40, 50]

In [2]:
arr[0]

10

In [3]:
arr[4]

50

In [11]:
arr1 = np.array([1,2,3,4,6,5])
arr1

array([1, 2, 3, 4, 6, 5])

In [12]:
print(arr1.shape)

(6,)


In [14]:
print(arr1.dtype)


int64


In [16]:
np.zeros([5])

array([0., 0., 0., 0., 0.])

In [17]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.ones([6])

array([1., 1., 1., 1., 1., 1.])

In [19]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [34]:
numbers = np.arange(0,10,2)
numbers


array([0, 2, 4, 6, 8])

In [48]:
arr2d =np.array([[1,2,3],[4,5,6]])
arr2d
print(arr2d.shape)
print(arr2d[0])
print(arr2d[1])
print(arr2d[1,1])

(2, 3)
[1 2 3]
[4 5 6]
5


In [52]:
sum_array = np.array([[1,2,3],[3,4,5]])
sum_array.sum()

np.int64(18)

In [56]:
print (sum_array.sum(axis=0))

[4 6 8]


In [68]:
lengtharr = np.array([10,20,30,40,50,60])
print(len(lengtharr))

6


In [70]:
A =np.array ([1,2,3]) 
B= np.array([4,5,6])
print(np.cross(A,B))


[-3  6 -3]


In [73]:
%timeit print("hello")


hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hell

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)



hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hell

In [87]:
ar2d = np.array ([[10,20,30],[40,50,60],[70,80,90]])
print(f"the complete array is : {ar2d}")
print(f"the shape is :  {ar2d.shape}")
print(f"the data type is : {ar2d.dtype}")
print(f"the sum is : {ar2d.sum()}")
print(f"the sum of each column is : {ar2d.sum(axis=0)}")
print(f"the first row is : {ar2d[0]}")
print(f"the last row is : {ar2d[2]}")
print(f"the value of 50 is : {ar2d[1,1]}")



the complete array is : [[10 20 30]
 [40 50 60]
 [70 80 90]]
the shape is :  (3, 3)
the data type is : int64
the sum is : 450
the sum of each column is : [120 150 180]
the first row is : [10 20 30]
the last row is : [70 80 90]
the value of 50 is : 50
